"""
============================================================
generate_pdf.py — GramSetu Receipt + Form Summary PDF
============================================================
Generates clean, professional PDFs with:
  - Form type + reference number
  - All submitted fields (PII masked)
  - Submission date + timestamp
  - GramSetu branding

No system dependencies — pure Python fpdf2.
"""
import base64
import os
from datetime import datetime
from fpdf import FPDF


class GramSetuPDF(FPDF):
    """Custom PDF with GramSetu branding."""

    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(15, 118, 110)  # Emerald green
        self.cell(0, 10, "GramSetu", ln=True, align="C")
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 6, "AI-Powered Government Form Assistant", ln=True, align="C")
        self.set_text_color(200, 200, 200)
        self.cell(0, 0, "", ln=True, border="B")
        self.ln(4)

    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(160, 160, 160)
        self.cell(0, 10, f"Generated by GramSetu AI on {datetime.now().strftime('%d %b %Y, %I:%M %p')} | This is a computer-generated document", align="C")


def generate_form_pdf(
    form_type: str,
    form_data: dict,
    reference_number: str,
    user_phone: str = "",
) -> bytes:
    """
    Generate a clean PDF receipt for a submitted form.
    Returns PDF as bytes.
    """
    pdf = GramSetuPDF()
    pdf.set_auto_page_break(auto=True, margin=25)
    pdf.add_page()

    # ── Title ──────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(30, 30, 30)
    form_label = form_type.replace("_", " ").title()
    pdf.cell(0, 12, f"{form_label} — Application Receipt", ln=True, align="C")
    pdf.ln(4)

    # ── Reference ──────────────────────────────────────────
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 8, f"Reference Number: {reference_number}", ln=True, align="C")
    pdf.cell(0, 8, f"Date: {datetime.now().strftime('%d %b %Y, %I:%M %p')}", ln=True, align="C")
    if user_phone:
        pdf.cell(0, 8, f"Mobile: +91XXXXXX{user_phone[-4:]}", ln=True, align="C")
    pdf.ln(8)

    # ── Fields Table ───────────────────────────────────────
    pdf.set_line_width(0.3)
    pdf.set_draw_color(220, 220, 220)

    # Table header
    pdf.set_fill_color(245, 245, 245)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(65, 8, "  Field", border=1, fill=True)
    pdf.cell(100, 8, "  Value", border=1, fill=True)
    pdf.ln()

    # Table rows
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(30, 30, 30)
    row_count = 0

    def write_row(field_name: str, value: str):
        nonlocal row_count
        # Mask PII
        display = str(value or "")
        fname = field_name.lower()
        if "aadhaar" in fname and len(display.replace(" ", "")) >= 4:
            display = f"XXXX-XXXX-{display.replace(' ', '').replace('-', '')[-4:]}"
        elif ("mobile" in fname or "phone" in fname) and len(display) >= 4:
            display = f"XXXXXX{display[-4:]}"
        elif "account" in fname and len(display) >= 4:
            display = f"XXXX{display[-4:]}"

        label = field_name.replace("_", " ").title()
        bg = (252, 252, 252) if row_count % 2 == 0 else (255, 255, 255)
        pdf.set_fill_color(*bg)
        pdf.cell(65, 7, f"  {label}", border=1, fill=True)
        pdf.cell(100, 7, f"  {display[:60]}", border=1, fill=True)
        pdf.ln()
        row_count += 1

    for field, value in form_data.items():
        if isinstance(value, dict):
            for sub_k, sub_v in value.items():
                if sub_v:
                    write_row(sub_k, str(sub_v))
        elif value:
            write_row(field, str(value))

    # ── Footer note ────────────────────────────────────────
    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(140, 140, 140)
    pdf.multi_cell(0, 5,
        "This is a computer-generated receipt from GramSetu. "
        "The actual application has been submitted on the government portal. "
        "You will receive confirmation via SMS on your registered mobile number. "
        "For any queries, contact your nearest CSC center or Gram Panchayat.",
        align="C"
    )

    return pdf.output()


def pdf_to_base64(pdf_bytes: bytes) -> str:
    """Convert PDF bytes to base64 string (for sending via Meta API)."""
    return base64.b64encode(pdf_bytes).decode()


def generate_and_encode(
    form_type: str,
    form_data: dict,
    reference_number: str,
    user_phone: str = "",
) -> str:
    """Generate PDF and return as base64."""
    pdf_bytes = generate_form_pdf(form_type, form_data, reference_number, user_phone)
    return pdf_to_base64(pdf_bytes)
